import type { Apartment, Building, Issue, MaintenanceRecord, Pipe, SystemType, Valve } from './types'

const floors = ['Basement', 'Floor 1', 'Floor 2', 'Floor 3', 'Floor 4', 'Floor 5', 'Floor 6', 'Roof']
const apartmentLetters = ['A', 'B', 'C', 'D']
const roomNames = ['Bathroom', 'Kitchen', 'Bedroom', 'Living Room', 'Hallway']

export const buildings: Building[] = [
  {
    id: 'bldg-124w83',
    name: '124 West 83rd Street',
    type: 'Mixed-use residential building',
    location: 'New York, NY',
    floors,
    units: 24,
    mechanicalRooms: ['Basement', 'Roof'],
    mappedSystems: ['Cold Water', 'Hot Water', 'Waste Line', 'Heating / Steam', 'Gas Line'],
    summary:
      'Pre-war six-story residential building with retail at grade, basement mechanical rooms, stacked wet walls, and roof-level heating equipment.',
  },
  {
    id: 'bldg-214madison',
    name: '214 Madison Avenue',
    type: 'Commercial office conversion',
    location: 'New York, NY',
    floors,
    units: 18,
    mechanicalRooms: ['Basement', 'Roof'],
    mappedSystems: ['Cold Water', 'Hot Water', 'Waste Line', 'Heating / Steam'],
    summary: 'Office-to-residential conversion with dense riser clusters and shared mechanical chases.',
  },
  {
    id: 'bldg-88brooklyn',
    name: '88 Brooklyn Heights',
    type: 'Boutique residential building',
    location: 'Brooklyn, NY',
    floors: ['Basement', 'Floor 1', 'Floor 2', 'Floor 3', 'Floor 4', 'Roof'],
    units: 16,
    mechanicalRooms: ['Basement'],
    mappedSystems: ['Cold Water', 'Hot Water', 'Waste Line', 'Gas Line'],
    summary: 'Low-rise masonry building with renovated kitchens and legacy waste line routing.',
  },
]

export const apartments: Apartment[] = floors.flatMap((floor) => {
  if (floor === 'Basement') {
    return [
      {
        id: 'basement-mech',
        floor,
        label: 'Mechanical Room',
        rooms: [
          {
            id: 'basement-mechanical-room',
            floor,
            apartment: 'Mechanical Room',
            name: 'Mechanical Room',
            notes: [
              'Main cold and hot water shut-offs on north wall.',
              'Heating loop and pressure gauges are accessible from the service aisle.',
              'Gas meter bank sits behind labeled lockable panel.',
            ],
          },
        ],
      },
    ]
  }

  if (floor === 'Roof') {
    return [
      {
        id: 'roof-mech',
        floor,
        label: 'Roof Mechanical',
        rooms: [
          {
            id: 'roof-mechanical-room',
            floor,
            apartment: 'Roof Mechanical',
            name: 'Mechanical Room',
            notes: [
              'Roof heating return line runs under pavers near the bulkhead.',
              'Access requires ladder and roof key from super office.',
            ],
          },
        ],
      },
    ]
  }

  const floorNumber = floor.replace('Floor ', '')
  return apartmentLetters.map((letter) => ({
    id: `${floorNumber}${letter}`,
    floor,
    label: `${floorNumber}${letter}`,
    rooms: roomNames.map((name) => ({
      id: `${floorNumber}${letter}-${name.toLowerCase().replaceAll(' ', '-')}`,
      floor,
      apartment: `${floorNumber}${letter}`,
      name,
      notes:
        name === 'Bathroom' && `${floorNumber}${letter}` === '3B'
          ? [
              'Cold water line behind east wall.',
              'Hot water riser near vanity.',
              'Waste line below bathtub.',
              'Shut-off valve in hallway access panel.',
              'Last repair: Feb 11, 2026.',
              'Related issue: Slow leak behind bathroom wall.',
            ]
          : [
              `${name} mapped with visible pipe routes and valve references.`,
              'Tap View in 3D to inspect nearby risers, shut-offs, and access points.',
            ],
    })),
  }))
})

const systemColor: Record<SystemType, string> = {
  'Cold Water': '#2f80ed',
  'Hot Water': '#f26a3d',
  'Waste Line': '#30343b',
  'Heating / Steam': '#8f63d9',
  'Gas Line': '#f4bd32',
}

const basePipes: Pipe[] = [
  {
    id: 'HW-3B-BATH-EAST',
    systemType: 'Hot Water',
    color: systemColor['Hot Water'],
    floor: 'Floor 3',
    apartment: '3B',
    room: 'Bathroom',
    startPoint: { x: 34, y: 44, z: 3 },
    endPoint: { x: 74, y: 32, z: 3 },
    material: 'Type L copper',
    diameter: '3/4 in',
    status: 'Watch',
    connectedValves: ['V-HW-3B-HALL', 'V-HW-BSMT-MAIN'],
    lastServiceDate: 'Feb 11, 2026',
    notes: 'Runs behind east bathroom wall and ties into vertical riser near vanity.',
  },
  {
    id: 'CW-3B-BATH-EAST',
    systemType: 'Cold Water',
    color: systemColor['Cold Water'],
    floor: 'Floor 3',
    apartment: '3B',
    room: 'Bathroom',
    startPoint: { x: 32, y: 50, z: 3 },
    endPoint: { x: 76, y: 39, z: 3 },
    material: 'Type L copper',
    diameter: '3/4 in',
    status: 'Normal',
    connectedValves: ['V-CW-3B-HALL', 'V-CW-BSMT-MAIN'],
    lastServiceDate: 'Mar 02, 2026',
    notes: 'Cold riser is accessible from hallway panel before entering bathroom wet wall.',
  },
  {
    id: 'WL-3B-TUB-STACK',
    systemType: 'Waste Line',
    color: systemColor['Waste Line'],
    floor: 'Floor 3',
    apartment: '3B',
    room: 'Bathroom',
    startPoint: { x: 26, y: 62, z: 3 },
    endPoint: { x: 72, y: 64, z: 2.8 },
    material: 'Cast iron',
    diameter: '2 in',
    status: 'Needs Service',
    connectedValves: [],
    lastServiceDate: 'Dec 08, 2025',
    notes: 'Tub trap line crosses below slab and connects to shared waste stack.',
  },
  {
    id: 'GAS-1A-KITCHEN',
    systemType: 'Gas Line',
    color: systemColor['Gas Line'],
    floor: 'Floor 1',
    apartment: '1A',
    room: 'Kitchen',
    startPoint: { x: 24, y: 72, z: 1 },
    endPoint: { x: 68, y: 54, z: 1 },
    material: 'Black steel',
    diameter: '1/2 in',
    status: 'Normal',
    connectedValves: ['V-GAS-1A-KIT'],
    lastServiceDate: 'Jan 05, 2026',
    notes: 'Dedicated range supply with accessible appliance shut-off.',
  },
  {
    id: 'STM-BSMT-LOOP',
    systemType: 'Heating / Steam',
    color: systemColor['Heating / Steam'],
    floor: 'Basement',
    apartment: 'Mechanical Room',
    room: 'Mechanical Room',
    startPoint: { x: 20, y: 72, z: 0 },
    endPoint: { x: 82, y: 44, z: 0 },
    material: 'Schedule 40 steel',
    diameter: '2 in',
    status: 'Watch',
    connectedValves: ['V-STM-BSMT-RETURN'],
    lastServiceDate: 'Sep 03, 2025',
    notes: 'Insulated heating loop feeding north riser bank.',
  },
  {
    id: 'CW-4-RISER-NORTH',
    systemType: 'Cold Water',
    color: systemColor['Cold Water'],
    floor: 'Floor 4',
    apartment: '4C',
    room: 'Hallway',
    startPoint: { x: 18, y: 36, z: 4 },
    endPoint: { x: 78, y: 30, z: 4 },
    material: 'Type L copper',
    diameter: '1 in',
    status: 'Normal',
    connectedValves: ['V-CW-4-HALL'],
    lastServiceDate: 'Nov 16, 2025',
    notes: 'North riser branch feeding C and D line bathrooms.',
  },
  {
    id: 'WL-2C-KITCHEN',
    systemType: 'Waste Line',
    color: systemColor['Waste Line'],
    floor: 'Floor 2',
    apartment: '2C',
    room: 'Kitchen',
    startPoint: { x: 44, y: 58, z: 2 },
    endPoint: { x: 84, y: 68, z: 2 },
    material: 'No-hub cast iron',
    diameter: '2 in',
    status: 'Watch',
    connectedValves: [],
    lastServiceDate: 'Dec 08, 2025',
    notes: 'Kitchen waste branch cleared after grease restriction near shared stack.',
  },
]

const generatedPipes: Pipe[] = apartmentLetters.flatMap((letter, index) => {
  return [1, 2, 3, 4, 5, 6].flatMap((floorNumber) => {
    const apartment = `${floorNumber}${letter}`
    const x = 18 + index * 18
    return [
      {
        id: `CW-${apartment}-RISER`,
        systemType: 'Cold Water' as const,
        color: systemColor['Cold Water'],
        floor: `Floor ${floorNumber}`,
        apartment,
        room: 'Kitchen',
        startPoint: { x, y: 26 + floorNumber * 3, z: floorNumber },
        endPoint: { x: x + 14, y: 42 + floorNumber * 2, z: floorNumber },
        material: 'Type L copper',
        diameter: '1/2 in',
        status: 'Normal' as const,
        connectedValves: [`V-CW-${apartment}`],
        lastServiceDate: 'Mar 18, 2026',
        notes: `Cold water branch feeding Apartment ${apartment} kitchen and bath fixtures.`,
      },
      {
        id: `HW-${apartment}-RISER`,
        systemType: 'Hot Water' as const,
        color: systemColor['Hot Water'],
        floor: `Floor ${floorNumber}`,
        apartment,
        room: 'Bathroom',
        startPoint: { x: x + 8, y: 30 + floorNumber * 3, z: floorNumber },
        endPoint: { x: x + 22, y: 48 + floorNumber * 2, z: floorNumber },
        material: 'Type L copper',
        diameter: '1/2 in',
        status: apartment === '3B' ? ('Watch' as const) : ('Normal' as const),
        connectedValves: [`V-HW-${apartment}`],
        lastServiceDate: apartment === '3B' ? 'Feb 11, 2026' : 'Mar 18, 2026',
        notes: `Hot water branch feeding Apartment ${apartment} wet wall.`,
      },
    ]
  })
})

export const pipes: Pipe[] = [...basePipes, ...generatedPipes]

export const valves: Valve[] = [
  {
    id: 'V-HW-3B-HALL',
    type: 'Quarter-turn shut-off',
    systemType: 'Hot Water',
    location: 'Floor 3 hallway access panel, outside Apartment 3B bathroom',
    floor: 'Floor 3',
    apartment: '3B',
    room: 'Hallway',
    controls: ['Apartment 3B Bathroom', 'Apartment 3B Kitchen hot branch'],
    accessibility: 'Panel access',
    lastTested: 'Mar 18, 2026',
    emergencyInstruction: 'Open labeled hallway panel, turn red handle clockwise until fully seated, then verify pressure drop at vanity.',
    point: { x: 77, y: 35, z: 3 },
  },
  {
    id: 'V-CW-3B-HALL',
    type: 'Ball valve',
    systemType: 'Cold Water',
    location: 'Floor 3 hallway access panel, blue handle',
    floor: 'Floor 3',
    apartment: '3B',
    room: 'Hallway',
    controls: ['Apartment 3B Bathroom cold water', 'Apartment 3B Kitchen cold water'],
    accessibility: 'Panel access',
    lastTested: 'Mar 18, 2026',
    emergencyInstruction: 'Turn blue handle perpendicular to pipe. Notify tenants before service interruption.',
    point: { x: 73, y: 42, z: 3 },
  },
  {
    id: 'V-HW-BSMT-MAIN',
    type: 'Main isolation valve',
    systemType: 'Hot Water',
    location: 'Basement mechanical room, north wall',
    floor: 'Basement',
    apartment: 'Mechanical Room',
    room: 'Mechanical Room',
    controls: ['All B-line hot water risers'],
    accessibility: 'Easy access',
    lastTested: 'Jan 22, 2026',
    emergencyInstruction: 'Use only if branch valve cannot isolate leak. Call property manager before full riser shutdown.',
    point: { x: 38, y: 68, z: 0 },
  },
  {
    id: 'V-CW-BSMT-MAIN',
    type: 'Main isolation valve',
    systemType: 'Cold Water',
    location: 'Basement mechanical room, domestic water manifold',
    floor: 'Basement',
    apartment: 'Mechanical Room',
    room: 'Mechanical Room',
    controls: ['All cold water risers'],
    accessibility: 'Easy access',
    lastTested: 'Jan 22, 2026',
    emergencyInstruction: 'Shut only during emergency or scheduled building-wide service.',
    point: { x: 30, y: 70, z: 0 },
  },
  {
    id: 'V-GAS-1A-KIT',
    type: 'Appliance shut-off',
    systemType: 'Gas Line',
    location: 'Apartment 1A kitchen, lower cabinet left of range',
    floor: 'Floor 1',
    apartment: '1A',
    room: 'Kitchen',
    controls: ['Apartment 1A range'],
    accessibility: 'Easy access',
    lastTested: 'Jan 05, 2026',
    emergencyInstruction: 'Turn valve perpendicular to pipe. If gas odor is present, evacuate and call utility emergency line.',
    point: { x: 68, y: 54, z: 1 },
  },
  {
    id: 'V-STM-BSMT-RETURN',
    type: 'Steam return isolation',
    systemType: 'Heating / Steam',
    location: 'Basement service aisle below north riser bank',
    floor: 'Basement',
    apartment: 'Mechanical Room',
    room: 'Mechanical Room',
    controls: ['North heating loop', 'B-line radiator branch'],
    accessibility: 'Needs ladder',
    lastTested: 'Sep 03, 2025',
    emergencyInstruction: 'Allow system to cool before service. Use gloves and verify pressure gauge reads zero.',
    point: { x: 82, y: 44, z: 0 },
  },
  {
    id: 'V-CW-4-HALL',
    type: 'Riser branch valve',
    systemType: 'Cold Water',
    location: 'Floor 4 north hallway chase',
    floor: 'Floor 4',
    apartment: '4C',
    room: 'Hallway',
    controls: ['Apartment 4C', 'Apartment 4D'],
    accessibility: 'Restricted',
    lastTested: 'Nov 16, 2025',
    emergencyInstruction: 'Requires super key. Remove chase cover and close blue lever.',
    point: { x: 78, y: 30, z: 4 },
  },
  ...apartmentLetters.flatMap((letter, index) =>
    [1, 2, 3, 4, 5, 6].flatMap((floorNumber) => {
      const apartment = `${floorNumber}${letter}`
      return [
        {
          id: `V-CW-${apartment}`,
          type: 'Fixture branch valve',
          systemType: 'Cold Water' as const,
          location: `Apartment ${apartment} kitchen sink base cabinet`,
          floor: `Floor ${floorNumber}`,
          apartment,
          room: 'Kitchen',
          controls: [`Apartment ${apartment} cold water fixtures`],
          accessibility: 'Easy access' as const,
          lastTested: 'Mar 18, 2026',
          emergencyInstruction: 'Close blue handle at cabinet valve and confirm fixture pressure stops.',
          point: { x: 20 + index * 18, y: 42 + floorNumber * 2, z: floorNumber },
        },
        {
          id: `V-HW-${apartment}`,
          type: 'Fixture branch valve',
          systemType: 'Hot Water' as const,
          location: `Apartment ${apartment} bathroom vanity base`,
          floor: `Floor ${floorNumber}`,
          apartment,
          room: 'Bathroom',
          controls: [`Apartment ${apartment} hot water fixtures`],
          accessibility: 'Easy access' as const,
          lastTested: apartment === '3B' ? 'Feb 11, 2026' : 'Mar 18, 2026',
          emergencyInstruction: 'Close red handle below vanity. If leak continues, use hallway access panel valve.',
          point: { x: 28 + index * 18, y: 48 + floorNumber * 2, z: floorNumber },
        },
      ]
    }),
  ),
]

export const issues: Issue[] = [
  {
    id: 'ISS-1007',
    title: 'Leak behind bathroom wall',
    severity: 'High',
    status: 'Investigating',
    floor: 'Floor 3',
    apartment: '3B',
    room: 'Bathroom',
    description: 'Tenant reports damp paint and bubbling plaster near vanity wall after evening hot water use.',
    suspectedPipeId: 'HW-3B-BATH-EAST',
    nearestValveId: 'V-HW-3B-HALL',
    reportedBy: 'M. Rivera, Superintendent',
    reportedDate: 'Apr 24, 2026',
    recommendedAction: 'Close hallway hot water branch valve, inspect vanity riser access, then open east wall only between studs 14-18.',
  },
  {
    id: 'ISS-1008',
    title: 'Slow drain at kitchen sink',
    severity: 'Medium',
    status: 'Scheduled',
    floor: 'Floor 2',
    apartment: '2C',
    room: 'Kitchen',
    description: 'Kitchen sink drains slowly after grease line service in December.',
    suspectedPipeId: 'WL-2C-KITCHEN',
    nearestValveId: 'V-CW-2C',
    reportedBy: 'Tenant portal',
    reportedDate: 'Apr 21, 2026',
    recommendedAction: 'Snake kitchen branch from sink cleanout before opening cabinet back panel.',
  },
  {
    id: 'ISS-1009',
    title: 'Low pressure on C-line',
    severity: 'Medium',
    status: 'New',
    floor: 'Floor 4',
    apartment: '4C',
    room: 'Bathroom',
    description: 'Low cold water pressure reported in 4C and 4D bathrooms.',
    suspectedPipeId: 'CW-4-RISER-NORTH',
    nearestValveId: 'V-CW-4-HALL',
    reportedBy: 'Evening porter',
    reportedDate: 'Apr 20, 2026',
    recommendedAction: 'Check north hallway branch valve and aerators before scheduling riser inspection.',
  },
  {
    id: 'ISS-1010',
    title: 'Steam knock at basement return',
    severity: 'Low',
    status: 'Investigating',
    floor: 'Basement',
    apartment: 'Mechanical Room',
    room: 'Mechanical Room',
    description: 'Intermittent noise from basement return loop during morning heat cycle.',
    suspectedPipeId: 'STM-BSMT-LOOP',
    nearestValveId: 'V-STM-BSMT-RETURN',
    reportedBy: 'Night super',
    reportedDate: 'Apr 18, 2026',
    recommendedAction: 'Verify return pitch, insulation condition, and trap operation before heating season closeout.',
  },
]

export const maintenanceRecords: MaintenanceRecord[] = [
  {
    id: 'MR-2201',
    date: 'Feb 11, 2026',
    location: 'Apartment 3B Bathroom',
    floor: 'Floor 3',
    apartment: '3B',
    room: 'Bathroom',
    systemType: 'Hot Water',
    description: 'Bathroom leak repair, replaced short copper section near vanity riser.',
    technician: 'Carmine Plumbing',
    costEstimate: '$1,950',
    relatedPipeId: 'HW-3B-BATH-EAST',
    relatedValveId: 'V-HW-3B-HALL',
    status: 'Completed',
    severity: 'High',
    notes: 'Wall opened 18 inches wide after confirming pipe path. Moisture remediation completed same day.',
  },
  {
    id: 'MR-2202',
    date: 'Jan 22, 2026',
    location: 'Basement Mechanical Room',
    floor: 'Basement',
    apartment: 'Mechanical Room',
    room: 'Mechanical Room',
    systemType: 'Hot Water',
    description: 'Hot water main valve replaced and branch valves tagged.',
    technician: 'Hudson Mechanical',
    costEstimate: '$2,800',
    relatedPipeId: 'HW-3B-BATH-EAST',
    relatedValveId: 'V-HW-BSMT-MAIN',
    status: 'Completed',
    severity: 'Medium',
    notes: 'Added red tags for B-line shut-offs and updated emergency instructions.',
  },
  {
    id: 'MR-2203',
    date: 'Dec 08, 2025',
    location: 'Apartment 2C Kitchen',
    floor: 'Floor 2',
    apartment: '2C',
    room: 'Kitchen',
    systemType: 'Waste Line',
    description: 'Waste line clog cleared from kitchen branch.',
    technician: 'Rapid Rooter NYC',
    costEstimate: '$680',
    relatedPipeId: 'WL-2C-KITCHEN',
    relatedValveId: 'V-CW-2C',
    status: 'Completed',
    severity: 'Medium',
    notes: 'Grease buildup at shared stack. Recommended enzyme maintenance for C-line units.',
  },
  {
    id: 'MR-2204',
    date: 'Nov 16, 2025',
    location: 'Floor 4 Riser',
    floor: 'Floor 4',
    apartment: '4C',
    room: 'Hallway',
    systemType: 'Cold Water',
    description: 'Pressure issue inspection on north riser.',
    technician: 'In-house maintenance',
    costEstimate: '$340',
    relatedPipeId: 'CW-4-RISER-NORTH',
    relatedValveId: 'V-CW-4-HALL',
    status: 'Needs follow-up',
    severity: 'Low',
    notes: 'Valve handle stiff but operable. Recommend replacement during next planned shut-down.',
  },
  {
    id: 'MR-2205',
    date: 'Sep 03, 2025',
    location: 'Basement Heating Loop',
    floor: 'Basement',
    apartment: 'Mechanical Room',
    room: 'Mechanical Room',
    systemType: 'Heating / Steam',
    description: 'Heating pipe insulation repaired.',
    technician: 'Hudson Mechanical',
    costEstimate: '$1,240',
    relatedPipeId: 'STM-BSMT-LOOP',
    relatedValveId: 'V-STM-BSMT-RETURN',
    status: 'Completed',
    severity: 'Medium',
    notes: 'Rewrapped 24 feet of return line and added warning tags near ladder access.',
  },
]

export const dashboardMetrics = {
  openIssues: 4,
  highPriority: 1,
  valvesMapped: 38,
  lastInspection: 'March 18, 2026',
  wallOpeningsAvoided: 12,
  savedCost: '$18,400',
}
